package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminid;
     private String name;
     private String email;
     private String password;
     private Integer districtid;
     private String district;

    public Admin() {
    }

    public Admin(String name, String email, String password, Integer districtid, String district) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.districtid = districtid;
       this.district = district;
    }
   
    public Integer getAdminid() {
        return this.adminid;
    }
    
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }




}


