package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Appointment generated by hbm2java
 */
public class Appointment  implements java.io.Serializable {


     private Integer appointmentid;
     private String bgname;
     private String bgnid;
     private String bgdop;
     private String bname;
     private String bnid;
     private String bdop;
     private String phone;
     private String address;
     private String mohor;
     private String mtype;
     private Date date;
     private Date apdate;
     private String messege;
     private String password;
     private String status;
     private String kazimessage;
     private String kaziid;
     private String kname;
     private String districtid;

    public Appointment() {
    }

    public Appointment(String bgname, String bgnid, String bgdop, String bname, String bnid, String bdop, String phone, String address, String mohor, String mtype, Date date, Date apdate, String messege, String password, String status, String kazimessage, String kaziid, String kname, String districtid) {
       this.bgname = bgname;
       this.bgnid = bgnid;
       this.bgdop = bgdop;
       this.bname = bname;
       this.bnid = bnid;
       this.bdop = bdop;
       this.phone = phone;
       this.address = address;
       this.mohor = mohor;
       this.mtype = mtype;
       this.date = date;
       this.apdate = apdate;
       this.messege = messege;
       this.password = password;
       this.status = status;
       this.kazimessage = kazimessage;
       this.kaziid = kaziid;
       this.kname = kname;
       this.districtid = districtid;
    }
   
    public Integer getAppointmentid() {
        return this.appointmentid;
    }
    
    public void setAppointmentid(Integer appointmentid) {
        this.appointmentid = appointmentid;
    }
    public String getBgname() {
        return this.bgname;
    }
    
    public void setBgname(String bgname) {
        this.bgname = bgname;
    }
    public String getBgnid() {
        return this.bgnid;
    }
    
    public void setBgnid(String bgnid) {
        this.bgnid = bgnid;
    }
    public String getBgdop() {
        return this.bgdop;
    }
    
    public void setBgdop(String bgdop) {
        this.bgdop = bgdop;
    }
    public String getBname() {
        return this.bname;
    }
    
    public void setBname(String bname) {
        this.bname = bname;
    }
    public String getBnid() {
        return this.bnid;
    }
    
    public void setBnid(String bnid) {
        this.bnid = bnid;
    }
    public String getBdop() {
        return this.bdop;
    }
    
    public void setBdop(String bdop) {
        this.bdop = bdop;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getMohor() {
        return this.mohor;
    }
    
    public void setMohor(String mohor) {
        this.mohor = mohor;
    }
    public String getMtype() {
        return this.mtype;
    }
    
    public void setMtype(String mtype) {
        this.mtype = mtype;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getApdate() {
        return this.apdate;
    }
    
    public void setApdate(Date apdate) {
        this.apdate = apdate;
    }
    public String getMessege() {
        return this.messege;
    }
    
    public void setMessege(String messege) {
        this.messege = messege;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getKazimessage() {
        return this.kazimessage;
    }
    
    public void setKazimessage(String kazimessage) {
        this.kazimessage = kazimessage;
    }
    public String getKaziid() {
        return this.kaziid;
    }
    
    public void setKaziid(String kaziid) {
        this.kaziid = kaziid;
    }
    public String getKname() {
        return this.kname;
    }
    
    public void setKname(String kname) {
        this.kname = kname;
    }
    public String getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(String districtid) {
        this.districtid = districtid;
    }




}


