package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1



/**
 * Bformdivorce generated by hbm2java
 */
public class Bformdivorce  implements java.io.Serializable {


     private int id;
     private String husband;
     private String hnid;
     private String wife;
     private String wnid;
     private String identifier;
     private String evidence;
     private String ddate;
     private String dowry;
     private String dplace;
     private String placeperson;
     private String dwithnesses;
     private String registerdate;
     private String divorcetype;
     private Double netpay;
     private String kaziid;
     private Integer districtid;
     private String district;
     private String fulladdress;

    public Bformdivorce() {
    }

	
    public Bformdivorce(int id) {
        this.id = id;
    }
    public Bformdivorce(int id, String husband, String hnid, String wife, String wnid, String identifier, String evidence, String ddate, String dowry, String dplace, String placeperson, String dwithnesses, String registerdate, String divorcetype, Double netpay, String kaziid, Integer districtid, String district, String fulladdress) {
       this.id = id;
       this.husband = husband;
       this.hnid = hnid;
       this.wife = wife;
       this.wnid = wnid;
       this.identifier = identifier;
       this.evidence = evidence;
       this.ddate = ddate;
       this.dowry = dowry;
       this.dplace = dplace;
       this.placeperson = placeperson;
       this.dwithnesses = dwithnesses;
       this.registerdate = registerdate;
       this.divorcetype = divorcetype;
       this.netpay = netpay;
       this.kaziid = kaziid;
       this.districtid = districtid;
       this.district = district;
       this.fulladdress = fulladdress;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getHusband() {
        return this.husband;
    }
    
    public void setHusband(String husband) {
        this.husband = husband;
    }
    public String getHnid() {
        return this.hnid;
    }
    
    public void setHnid(String hnid) {
        this.hnid = hnid;
    }
    public String getWife() {
        return this.wife;
    }
    
    public void setWife(String wife) {
        this.wife = wife;
    }
    public String getWnid() {
        return this.wnid;
    }
    
    public void setWnid(String wnid) {
        this.wnid = wnid;
    }
    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }
    public String getEvidence() {
        return this.evidence;
    }
    
    public void setEvidence(String evidence) {
        this.evidence = evidence;
    }
    public String getDdate() {
        return this.ddate;
    }
    
    public void setDdate(String ddate) {
        this.ddate = ddate;
    }
    public String getDowry() {
        return this.dowry;
    }
    
    public void setDowry(String dowry) {
        this.dowry = dowry;
    }
    public String getDplace() {
        return this.dplace;
    }
    
    public void setDplace(String dplace) {
        this.dplace = dplace;
    }
    public String getPlaceperson() {
        return this.placeperson;
    }
    
    public void setPlaceperson(String placeperson) {
        this.placeperson = placeperson;
    }
    public String getDwithnesses() {
        return this.dwithnesses;
    }
    
    public void setDwithnesses(String dwithnesses) {
        this.dwithnesses = dwithnesses;
    }
    public String getRegisterdate() {
        return this.registerdate;
    }
    
    public void setRegisterdate(String registerdate) {
        this.registerdate = registerdate;
    }
    public String getDivorcetype() {
        return this.divorcetype;
    }
    
    public void setDivorcetype(String divorcetype) {
        this.divorcetype = divorcetype;
    }
    public Double getNetpay() {
        return this.netpay;
    }
    
    public void setNetpay(Double netpay) {
        this.netpay = netpay;
    }
    public String getKaziid() {
        return this.kaziid;
    }
    
    public void setKaziid(String kaziid) {
        this.kaziid = kaziid;
    }
    public Integer getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getFulladdress() {
        return this.fulladdress;
    }
    
    public void setFulladdress(String fulladdress) {
        this.fulladdress = fulladdress;
    }




}


