package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1



/**
 * Cformdivorce generated by hbm2java
 */
public class Cformdivorce  implements java.io.Serializable {


     private int id;
     private String husband;
     private String hnid;
     private String wife;
     private String wnid;
     private String kholadate;
     private String mohor;
     private String acceptedbywife;
     private String witnessofkhola;
     private String kholawakilaccept;
     private String kholawitness;
     private String dplace;
     private String placeperson;
     private String kholawithnesses;
     private String hasbandwitness;
     private String registerdate;
     private Double netpay;
     private String kaziid;
     private Integer districtid;
     private String district;
     private String fulladdress;

    public Cformdivorce() {
    }

	
    public Cformdivorce(int id) {
        this.id = id;
    }
    public Cformdivorce(int id, String husband, String hnid, String wife, String wnid, String kholadate, String mohor, String acceptedbywife, String witnessofkhola, String kholawakilaccept, String kholawitness, String dplace, String placeperson, String kholawithnesses, String hasbandwitness, String registerdate, Double netpay, String kaziid, Integer districtid, String district, String fulladdress) {
       this.id = id;
       this.husband = husband;
       this.hnid = hnid;
       this.wife = wife;
       this.wnid = wnid;
       this.kholadate = kholadate;
       this.mohor = mohor;
       this.acceptedbywife = acceptedbywife;
       this.witnessofkhola = witnessofkhola;
       this.kholawakilaccept = kholawakilaccept;
       this.kholawitness = kholawitness;
       this.dplace = dplace;
       this.placeperson = placeperson;
       this.kholawithnesses = kholawithnesses;
       this.hasbandwitness = hasbandwitness;
       this.registerdate = registerdate;
       this.netpay = netpay;
       this.kaziid = kaziid;
       this.districtid = districtid;
       this.district = district;
       this.fulladdress = fulladdress;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getHusband() {
        return this.husband;
    }
    
    public void setHusband(String husband) {
        this.husband = husband;
    }
    public String getHnid() {
        return this.hnid;
    }
    
    public void setHnid(String hnid) {
        this.hnid = hnid;
    }
    public String getWife() {
        return this.wife;
    }
    
    public void setWife(String wife) {
        this.wife = wife;
    }
    public String getWnid() {
        return this.wnid;
    }
    
    public void setWnid(String wnid) {
        this.wnid = wnid;
    }
    public String getKholadate() {
        return this.kholadate;
    }
    
    public void setKholadate(String kholadate) {
        this.kholadate = kholadate;
    }
    public String getMohor() {
        return this.mohor;
    }
    
    public void setMohor(String mohor) {
        this.mohor = mohor;
    }
    public String getAcceptedbywife() {
        return this.acceptedbywife;
    }
    
    public void setAcceptedbywife(String acceptedbywife) {
        this.acceptedbywife = acceptedbywife;
    }
    public String getWitnessofkhola() {
        return this.witnessofkhola;
    }
    
    public void setWitnessofkhola(String witnessofkhola) {
        this.witnessofkhola = witnessofkhola;
    }
    public String getKholawakilaccept() {
        return this.kholawakilaccept;
    }
    
    public void setKholawakilaccept(String kholawakilaccept) {
        this.kholawakilaccept = kholawakilaccept;
    }
    public String getKholawitness() {
        return this.kholawitness;
    }
    
    public void setKholawitness(String kholawitness) {
        this.kholawitness = kholawitness;
    }
    public String getDplace() {
        return this.dplace;
    }
    
    public void setDplace(String dplace) {
        this.dplace = dplace;
    }
    public String getPlaceperson() {
        return this.placeperson;
    }
    
    public void setPlaceperson(String placeperson) {
        this.placeperson = placeperson;
    }
    public String getKholawithnesses() {
        return this.kholawithnesses;
    }
    
    public void setKholawithnesses(String kholawithnesses) {
        this.kholawithnesses = kholawithnesses;
    }
    public String getHasbandwitness() {
        return this.hasbandwitness;
    }
    
    public void setHasbandwitness(String hasbandwitness) {
        this.hasbandwitness = hasbandwitness;
    }
    public String getRegisterdate() {
        return this.registerdate;
    }
    
    public void setRegisterdate(String registerdate) {
        this.registerdate = registerdate;
    }
    public Double getNetpay() {
        return this.netpay;
    }
    
    public void setNetpay(Double netpay) {
        this.netpay = netpay;
    }
    public String getKaziid() {
        return this.kaziid;
    }
    
    public void setKaziid(String kaziid) {
        this.kaziid = kaziid;
    }
    public Integer getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getFulladdress() {
        return this.fulladdress;
    }
    
    public void setFulladdress(String fulladdress) {
        this.fulladdress = fulladdress;
    }




}


