package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1



/**
 * Kaziappro generated by hbm2java
 */
public class Kaziappro  implements java.io.Serializable {


     private Integer approvalid;
     private int kaziid;
     private String district;
     private Integer districtid;
     private String ps;
     private String unionn;
     private String nklicence;
     private String kname;
     private String nid;
     private String contact;
     private String email;
     private String approval;
     private String status;
     private String password;

    public Kaziappro() {
    }

	
    public Kaziappro(int kaziid) {
        this.kaziid = kaziid;
    }
    public Kaziappro(int kaziid, String district, Integer districtid, String ps, String unionn, String nklicence, String kname, String nid, String contact, String email, String approval, String status, String password) {
       this.kaziid = kaziid;
       this.district = district;
       this.districtid = districtid;
       this.ps = ps;
       this.unionn = unionn;
       this.nklicence = nklicence;
       this.kname = kname;
       this.nid = nid;
       this.contact = contact;
       this.email = email;
       this.approval = approval;
       this.status = status;
       this.password = password;
    }
   
    public Integer getApprovalid() {
        return this.approvalid;
    }
    
    public void setApprovalid(Integer approvalid) {
        this.approvalid = approvalid;
    }
    public int getKaziid() {
        return this.kaziid;
    }
    
    public void setKaziid(int kaziid) {
        this.kaziid = kaziid;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public Integer getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
    public String getPs() {
        return this.ps;
    }
    
    public void setPs(String ps) {
        this.ps = ps;
    }
    public String getUnionn() {
        return this.unionn;
    }
    
    public void setUnionn(String unionn) {
        this.unionn = unionn;
    }
    public String getNklicence() {
        return this.nklicence;
    }
    
    public void setNklicence(String nklicence) {
        this.nklicence = nklicence;
    }
    public String getKname() {
        return this.kname;
    }
    
    public void setKname(String kname) {
        this.kname = kname;
    }
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getApproval() {
        return this.approval;
    }
    
    public void setApproval(String approval) {
        this.approval = approval;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


