package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1



/**
 * Kazi generated by hbm2java
 */
public class Kazi  implements java.io.Serializable {


     private Integer kaziid;
     private String district;
     private Integer districtid;
     private String ps;
     private String unionn;
     private String fulladdress;
     private String nklicence;
     private String kname;
     private String fname;
     private String mname;
     private String nid;
     private String contact;
     private String email;
     private String qualification;
     private String photo;
     private String approval;
     private String status;

    public Kazi() {
    }

    public Kazi(String district, Integer districtid, String ps, String unionn, String fulladdress, String nklicence, String kname, String fname, String mname, String nid, String contact, String email, String qualification, String photo, String approval, String status) {
       this.district = district;
       this.districtid = districtid;
       this.ps = ps;
       this.unionn = unionn;
       this.fulladdress = fulladdress;
       this.nklicence = nklicence;
       this.kname = kname;
       this.fname = fname;
       this.mname = mname;
       this.nid = nid;
       this.contact = contact;
       this.email = email;
       this.qualification = qualification;
       this.photo = photo;
       this.approval = approval;
       this.status = status;
    }
   
    public Integer getKaziid() {
        return this.kaziid;
    }
    
    public void setKaziid(Integer kaziid) {
        this.kaziid = kaziid;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public Integer getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
    public String getPs() {
        return this.ps;
    }
    
    public void setPs(String ps) {
        this.ps = ps;
    }
    public String getUnionn() {
        return this.unionn;
    }
    
    public void setUnionn(String unionn) {
        this.unionn = unionn;
    }
    public String getFulladdress() {
        return this.fulladdress;
    }
    
    public void setFulladdress(String fulladdress) {
        this.fulladdress = fulladdress;
    }
    public String getNklicence() {
        return this.nklicence;
    }
    
    public void setNklicence(String nklicence) {
        this.nklicence = nklicence;
    }
    public String getKname() {
        return this.kname;
    }
    
    public void setKname(String kname) {
        this.kname = kname;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getApproval() {
        return this.approval;
    }
    
    public void setApproval(String approval) {
        this.approval = approval;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


