package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer payid;
     private String feeid;
     private String appointmentid;
     private String bgname;
     private String bname;
     private String bnd;
     private String mohor;
     private String fee;
     private Date paydate;
     private Double netpay;
     private Double revenue;
     private String paystatus;
     private String kaziid;
     private Integer districtid;
     private String district;
     private String fulladdress;
     private String fname;

    public Payment() {
    }

    public Payment(String feeid, String appointmentid, String bgname, String bname, String bnd, String mohor, String fee, Date paydate, Double netpay, Double revenue, String paystatus, String kaziid, Integer districtid, String district, String fulladdress, String fname) {
       this.feeid = feeid;
       this.appointmentid = appointmentid;
       this.bgname = bgname;
       this.bname = bname;
       this.bnd = bnd;
       this.mohor = mohor;
       this.fee = fee;
       this.paydate = paydate;
       this.netpay = netpay;
       this.revenue = revenue;
       this.paystatus = paystatus;
       this.kaziid = kaziid;
       this.districtid = districtid;
       this.district = district;
       this.fulladdress = fulladdress;
       this.fname = fname;
    }
   
    public Integer getPayid() {
        return this.payid;
    }
    
    public void setPayid(Integer payid) {
        this.payid = payid;
    }
    public String getFeeid() {
        return this.feeid;
    }
    
    public void setFeeid(String feeid) {
        this.feeid = feeid;
    }
    public String getAppointmentid() {
        return this.appointmentid;
    }
    
    public void setAppointmentid(String appointmentid) {
        this.appointmentid = appointmentid;
    }
    public String getBgname() {
        return this.bgname;
    }
    
    public void setBgname(String bgname) {
        this.bgname = bgname;
    }
    public String getBname() {
        return this.bname;
    }
    
    public void setBname(String bname) {
        this.bname = bname;
    }
    public String getBnd() {
        return this.bnd;
    }
    
    public void setBnd(String bnd) {
        this.bnd = bnd;
    }
    public String getMohor() {
        return this.mohor;
    }
    
    public void setMohor(String mohor) {
        this.mohor = mohor;
    }
    public String getFee() {
        return this.fee;
    }
    
    public void setFee(String fee) {
        this.fee = fee;
    }
    public Date getPaydate() {
        return this.paydate;
    }
    
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }
    public Double getNetpay() {
        return this.netpay;
    }
    
    public void setNetpay(Double netpay) {
        this.netpay = netpay;
    }
    public Double getRevenue() {
        return this.revenue;
    }
    
    public void setRevenue(Double revenue) {
        this.revenue = revenue;
    }
    public String getPaystatus() {
        return this.paystatus;
    }
    
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus;
    }
    public String getKaziid() {
        return this.kaziid;
    }
    
    public void setKaziid(String kaziid) {
        this.kaziid = kaziid;
    }
    public Integer getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getFulladdress() {
        return this.fulladdress;
    }
    
    public void setFulladdress(String fulladdress) {
        this.fulladdress = fulladdress;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }




}


