package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1



/**
 * Registration generated by hbm2java
 */
public class Registration  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String marriageplace;
     private String bgname;
     private String bgage;
     private String bname;
     private String btype;
     private String bage;
     private String byakil;
     private String byakilwitness;
     private String bgyakil;
     private String bgyakilwitness;
     private String marriagewitness;
     private String marriagedate;
     private Double denmohor;
     private String dowarmuajjal;
     private String denmohorpaid;
     private String property;
     private String condition;
     private String powerofdivorce;
     private String husbandrightofdivorce;
     private String dowerpaper;
     private String marriagetype;
     private String permissionnumber;
     private String solemnizer;
     private String mrdate;
     private Double netpay;
     private String kaziid;
     private Integer districtid;
     private String district;
     private String fulladdress;
     private String paydate;
     private String paystatus;
     private String conjugalstatus;

    public Registration() {
    }

    public Registration(String fname, String marriageplace, String bgname, String bgage, String bname, String btype, String bage, String byakil, String byakilwitness, String bgyakil, String bgyakilwitness, String marriagewitness, String marriagedate, Double denmohor, String dowarmuajjal, String denmohorpaid, String property, String condition, String powerofdivorce, String husbandrightofdivorce, String dowerpaper, String marriagetype, String permissionnumber, String solemnizer, String mrdate, Double netpay, String kaziid, Integer districtid, String district, String fulladdress, String paydate, String paystatus, String conjugalstatus) {
       this.fname = fname;
       this.marriageplace = marriageplace;
       this.bgname = bgname;
       this.bgage = bgage;
       this.bname = bname;
       this.btype = btype;
       this.bage = bage;
       this.byakil = byakil;
       this.byakilwitness = byakilwitness;
       this.bgyakil = bgyakil;
       this.bgyakilwitness = bgyakilwitness;
       this.marriagewitness = marriagewitness;
       this.marriagedate = marriagedate;
       this.denmohor = denmohor;
       this.dowarmuajjal = dowarmuajjal;
       this.denmohorpaid = denmohorpaid;
       this.property = property;
       this.condition = condition;
       this.powerofdivorce = powerofdivorce;
       this.husbandrightofdivorce = husbandrightofdivorce;
       this.dowerpaper = dowerpaper;
       this.marriagetype = marriagetype;
       this.permissionnumber = permissionnumber;
       this.solemnizer = solemnizer;
       this.mrdate = mrdate;
       this.netpay = netpay;
       this.kaziid = kaziid;
       this.districtid = districtid;
       this.district = district;
       this.fulladdress = fulladdress;
       this.paydate = paydate;
       this.paystatus = paystatus;
       this.conjugalstatus = conjugalstatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMarriageplace() {
        return this.marriageplace;
    }
    
    public void setMarriageplace(String marriageplace) {
        this.marriageplace = marriageplace;
    }
    public String getBgname() {
        return this.bgname;
    }
    
    public void setBgname(String bgname) {
        this.bgname = bgname;
    }
    public String getBgage() {
        return this.bgage;
    }
    
    public void setBgage(String bgage) {
        this.bgage = bgage;
    }
    public String getBname() {
        return this.bname;
    }
    
    public void setBname(String bname) {
        this.bname = bname;
    }
    public String getBtype() {
        return this.btype;
    }
    
    public void setBtype(String btype) {
        this.btype = btype;
    }
    public String getBage() {
        return this.bage;
    }
    
    public void setBage(String bage) {
        this.bage = bage;
    }
    public String getByakil() {
        return this.byakil;
    }
    
    public void setByakil(String byakil) {
        this.byakil = byakil;
    }
    public String getByakilwitness() {
        return this.byakilwitness;
    }
    
    public void setByakilwitness(String byakilwitness) {
        this.byakilwitness = byakilwitness;
    }
    public String getBgyakil() {
        return this.bgyakil;
    }
    
    public void setBgyakil(String bgyakil) {
        this.bgyakil = bgyakil;
    }
    public String getBgyakilwitness() {
        return this.bgyakilwitness;
    }
    
    public void setBgyakilwitness(String bgyakilwitness) {
        this.bgyakilwitness = bgyakilwitness;
    }
    public String getMarriagewitness() {
        return this.marriagewitness;
    }
    
    public void setMarriagewitness(String marriagewitness) {
        this.marriagewitness = marriagewitness;
    }
    public String getMarriagedate() {
        return this.marriagedate;
    }
    
    public void setMarriagedate(String marriagedate) {
        this.marriagedate = marriagedate;
    }
    public Double getDenmohor() {
        return this.denmohor;
    }
    
    public void setDenmohor(Double denmohor) {
        this.denmohor = denmohor;
    }
    public String getDowarmuajjal() {
        return this.dowarmuajjal;
    }
    
    public void setDowarmuajjal(String dowarmuajjal) {
        this.dowarmuajjal = dowarmuajjal;
    }
    public String getDenmohorpaid() {
        return this.denmohorpaid;
    }
    
    public void setDenmohorpaid(String denmohorpaid) {
        this.denmohorpaid = denmohorpaid;
    }
    public String getProperty() {
        return this.property;
    }
    
    public void setProperty(String property) {
        this.property = property;
    }
    public String getCondition() {
        return this.condition;
    }
    
    public void setCondition(String condition) {
        this.condition = condition;
    }
    public String getPowerofdivorce() {
        return this.powerofdivorce;
    }
    
    public void setPowerofdivorce(String powerofdivorce) {
        this.powerofdivorce = powerofdivorce;
    }
    public String getHusbandrightofdivorce() {
        return this.husbandrightofdivorce;
    }
    
    public void setHusbandrightofdivorce(String husbandrightofdivorce) {
        this.husbandrightofdivorce = husbandrightofdivorce;
    }
    public String getDowerpaper() {
        return this.dowerpaper;
    }
    
    public void setDowerpaper(String dowerpaper) {
        this.dowerpaper = dowerpaper;
    }
    public String getMarriagetype() {
        return this.marriagetype;
    }
    
    public void setMarriagetype(String marriagetype) {
        this.marriagetype = marriagetype;
    }
    public String getPermissionnumber() {
        return this.permissionnumber;
    }
    
    public void setPermissionnumber(String permissionnumber) {
        this.permissionnumber = permissionnumber;
    }
    public String getSolemnizer() {
        return this.solemnizer;
    }
    
    public void setSolemnizer(String solemnizer) {
        this.solemnizer = solemnizer;
    }
    public String getMrdate() {
        return this.mrdate;
    }
    
    public void setMrdate(String mrdate) {
        this.mrdate = mrdate;
    }
    public Double getNetpay() {
        return this.netpay;
    }
    
    public void setNetpay(Double netpay) {
        this.netpay = netpay;
    }
    public String getKaziid() {
        return this.kaziid;
    }
    
    public void setKaziid(String kaziid) {
        this.kaziid = kaziid;
    }
    public Integer getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getFulladdress() {
        return this.fulladdress;
    }
    
    public void setFulladdress(String fulladdress) {
        this.fulladdress = fulladdress;
    }
    public String getPaydate() {
        return this.paydate;
    }
    
    public void setPaydate(String paydate) {
        this.paydate = paydate;
    }
    public String getPaystatus() {
        return this.paystatus;
    }
    
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus;
    }
    public String getConjugalstatus() {
        return this.conjugalstatus;
    }
    
    public void setConjugalstatus(String conjugalstatus) {
        this.conjugalstatus = conjugalstatus;
    }




}


