package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Seekers generated by hbm2java
 */
public class Seekers  implements java.io.Serializable {


     private Integer sid;
     private String forname;
     private String surname;
     private String fname;
     private String mname;
     private Date dob;
     private String sex;
     private String religion;
     private String education;
     private String edusub;
     private String homedistrict;
     private String profession;
     private String pfield;
     private String pplace;
     private String familystatus;
     private String email;
     private String contact;
     private Double weight;
     private Double height;
     private String facecolor;

    public Seekers() {
    }

    public Seekers(String forname, String surname, String fname, String mname, Date dob, String sex, String religion, String education, String edusub, String homedistrict, String profession, String pfield, String pplace, String familystatus, String email, String contact, Double weight, Double height, String facecolor) {
       this.forname = forname;
       this.surname = surname;
       this.fname = fname;
       this.mname = mname;
       this.dob = dob;
       this.sex = sex;
       this.religion = religion;
       this.education = education;
       this.edusub = edusub;
       this.homedistrict = homedistrict;
       this.profession = profession;
       this.pfield = pfield;
       this.pplace = pplace;
       this.familystatus = familystatus;
       this.email = email;
       this.contact = contact;
       this.weight = weight;
       this.height = height;
       this.facecolor = facecolor;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public String getForname() {
        return this.forname;
    }
    
    public void setForname(String forname) {
        this.forname = forname;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }
    public String getEdusub() {
        return this.edusub;
    }
    
    public void setEdusub(String edusub) {
        this.edusub = edusub;
    }
    public String getHomedistrict() {
        return this.homedistrict;
    }
    
    public void setHomedistrict(String homedistrict) {
        this.homedistrict = homedistrict;
    }
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }
    public String getPfield() {
        return this.pfield;
    }
    
    public void setPfield(String pfield) {
        this.pfield = pfield;
    }
    public String getPplace() {
        return this.pplace;
    }
    
    public void setPplace(String pplace) {
        this.pplace = pplace;
    }
    public String getFamilystatus() {
        return this.familystatus;
    }
    
    public void setFamilystatus(String familystatus) {
        this.familystatus = familystatus;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public Double getHeight() {
        return this.height;
    }
    
    public void setHeight(Double height) {
        this.height = height;
    }
    public String getFacecolor() {
        return this.facecolor;
    }
    
    public void setFacecolor(String facecolor) {
        this.facecolor = facecolor;
    }




}


