package com.exam;
// Generated Jul 1, 2019 1:59:54 AM by Hibernate Tools 4.3.1



/**
 * Yoformdivorce generated by hbm2java
 */
public class Yoformdivorce  implements java.io.Serializable {


     private int id;
     private String husband;
     private String hnid;
     private String wife;
     private String wnid;
     private String ddate;
     private String dtype;
     private String dvdtype;
     private String dplace;
     private String placeperson;
     private String dwithnesses;
     private String identifiered;
     private String registerdate;
     private Double netpay;
     private String kaziid;
     private Integer districtid;
     private String district;
     private String fulladdress;

    public Yoformdivorce() {
    }

	
    public Yoformdivorce(int id) {
        this.id = id;
    }
    public Yoformdivorce(int id, String husband, String hnid, String wife, String wnid, String ddate, String dtype, String dvdtype, String dplace, String placeperson, String dwithnesses, String identifiered, String registerdate, Double netpay, String kaziid, Integer districtid, String district, String fulladdress) {
       this.id = id;
       this.husband = husband;
       this.hnid = hnid;
       this.wife = wife;
       this.wnid = wnid;
       this.ddate = ddate;
       this.dtype = dtype;
       this.dvdtype = dvdtype;
       this.dplace = dplace;
       this.placeperson = placeperson;
       this.dwithnesses = dwithnesses;
       this.identifiered = identifiered;
       this.registerdate = registerdate;
       this.netpay = netpay;
       this.kaziid = kaziid;
       this.districtid = districtid;
       this.district = district;
       this.fulladdress = fulladdress;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getHusband() {
        return this.husband;
    }
    
    public void setHusband(String husband) {
        this.husband = husband;
    }
    public String getHnid() {
        return this.hnid;
    }
    
    public void setHnid(String hnid) {
        this.hnid = hnid;
    }
    public String getWife() {
        return this.wife;
    }
    
    public void setWife(String wife) {
        this.wife = wife;
    }
    public String getWnid() {
        return this.wnid;
    }
    
    public void setWnid(String wnid) {
        this.wnid = wnid;
    }
    public String getDdate() {
        return this.ddate;
    }
    
    public void setDdate(String ddate) {
        this.ddate = ddate;
    }
    public String getDtype() {
        return this.dtype;
    }
    
    public void setDtype(String dtype) {
        this.dtype = dtype;
    }
    public String getDvdtype() {
        return this.dvdtype;
    }
    
    public void setDvdtype(String dvdtype) {
        this.dvdtype = dvdtype;
    }
    public String getDplace() {
        return this.dplace;
    }
    
    public void setDplace(String dplace) {
        this.dplace = dplace;
    }
    public String getPlaceperson() {
        return this.placeperson;
    }
    
    public void setPlaceperson(String placeperson) {
        this.placeperson = placeperson;
    }
    public String getDwithnesses() {
        return this.dwithnesses;
    }
    
    public void setDwithnesses(String dwithnesses) {
        this.dwithnesses = dwithnesses;
    }
    public String getIdentifiered() {
        return this.identifiered;
    }
    
    public void setIdentifiered(String identifiered) {
        this.identifiered = identifiered;
    }
    public String getRegisterdate() {
        return this.registerdate;
    }
    
    public void setRegisterdate(String registerdate) {
        this.registerdate = registerdate;
    }
    public Double getNetpay() {
        return this.netpay;
    }
    
    public void setNetpay(Double netpay) {
        this.netpay = netpay;
    }
    public String getKaziid() {
        return this.kaziid;
    }
    
    public void setKaziid(String kaziid) {
        this.kaziid = kaziid;
    }
    public Integer getDistrictid() {
        return this.districtid;
    }
    
    public void setDistrictid(Integer districtid) {
        this.districtid = districtid;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getFulladdress() {
        return this.fulladdress;
    }
    
    public void setFulladdress(String fulladdress) {
        this.fulladdress = fulladdress;
    }




}


